Working test version of cmake_six

diff --git a/SixTrack/cmake_six b/SixTrack/cmake_six
--- a/SixTrack/cmake_six
+++ b/SixTrack/cmake_six
@@ -1,9 +1,14 @@
 #! /usr/bin/env bash
 
 # make_six-like wrapper for cmake and make
-# 
+# To run it, say (for example) "./cmake_six 64BIT -32BIT nagfor"
+# To see all available options, run ./cmake_six --help (TODO: Implement this...)
 
-set -e
+set -e #Stop on error
+
+#For debugging
+#set -v
+#set -x
 
 echo "Welcome to cmake_six, camouflaging cmake and make inside the same interface as make_six !"
 
@@ -54,11 +59,12 @@ else
     echo "This is needed to check the correctness of the ASTUCE +if /+ei"
     echo "If you are modifying the .s files, it is STRONGLY RECCOMENDED to install gawk"
 fi
+echo ""
 
 #Get options
-
-compilers=(gfortran ifort ifort_icc nagfor) # Valid compilers
-options_COMPILER=notset #which compilers to use
+compilers=(default gfortran ifort ifort_icc nagfor) # Valid compilers. default = system default
+compilers_CMAKE=('' '-DCMAKE_Fortran_COMPILER=gfortran' '-DCMAKE_Fortran_COMPILER=ifort' '' '-DCMAKE_Fortran_COMPILER=nagfor')
+options_COMPILER=default #which compilers to use
 
 options_ALL=() # All set options
 options_ON=()  # All options switched ON
@@ -86,7 +92,7 @@ do
 	done
 	
 	options_ALL+=(${var:1})
-	
+	options_OFF+=(${var:1})
     else                      ## Positive options
 	#echo "ON" $var
 	varOn=$var
@@ -102,7 +108,7 @@ do
 	for v in ${compilers[@]}
 	do
 	    if [[ $v == $varOn ]]; then
-		if [[ $options_COMPILER != "notset" ]]; then
+		if [[ $options_COMPILER != "default" ]]; then
 		    echo "ERROR: can't set multiple compilers"
 		    exit 1
 		fi
@@ -113,17 +119,80 @@ do
 
 	if [[ $thisWasCompiler == "NO" ]]; then
 	    options_ALL+=($var)
+	    options_ON+=($var)	
 	fi
 	thisWasCompiler="NO"
     fi
 done
+#Sort the options
+# http://stackoverflow.com/questions/7442417/how-to-sort-an-array-in-bash
+IFS=$'\n' options_sorted_ALL=($(sort <<<"${options_ALL[*]}"))
+IFS=$'\n' options_sorted_ON=($(sort <<<"${options_ON[*]}"))
+IFS=$'\n' options_sorted_OFF=($(sort <<<"${options_OFF[*]}"))
 
-echo "got:"
-for var in ${options_ALL[@]}
+echo "options_ON  =" ${options_sorted_ON[@]}
+echo "options_OFF =" ${options_sorted_OFF[@]}
+
+#Build compiler options
+CMAKE_OPTIONS_LIST=""
+for i in $(seq 0 $(expr ${#compilers[@]} - 1 ) )
 do
-    echo $var
+    #echo $i ${compilers[$i]} ${compilers_CMAKE[$i]}
+    if [ $options_COMPILER == ${compilers[$i]} ]; then
+	#echo "FOUND!"
+	CMAKE_OPTIONS_LIST+=${compilers_CMAKE[$i]}
+    fi
 done
 
+#Make folder & build cmake options list
+NAME="SixTrack_cmakesix"
+
+for opt in ${options_sorted_ON[@]}
+do
+    NAME+=_$opt
+    CMAKE_OPTIONS_LIST+=" -D$opt=ON"
+done
+for opt in ${options_sorted_OFF[@]}
+do
+    NAME+=_NO$opt
+    CMAKE_OPTIONS_LIST+=" -D$opt=OFF"
+done
+NAME+=_$options_COMPILER
+
+echo $NAME
+
+if [ -d $NAME ]; then
+    echo "Folder '"$NAME"' already exists, deleting!"
+    rm -rf $NAME
+fi
+mkdir $NAME
 
 #Run cmake
+cd $NAME
+echo $(pwd)
+echo $CMAKE_OPTIONS_LIST
+
+set +e #From here on we catch errors manually...
+
+#Use EVAL to split the options from $CMAKE_OPTIONS_LIST
+# http://stackoverflow.com/questions/6087494/bash-inserting-quotes-into-string-before-execution
+eval cmake  $CMAKE_OPTIONS_LIST ../../.
+
+if [ $? != 0 ]; then
+    echo ""
+    echo "ERROR in CMAKE"
+    echo "Most likely you specified a bad argument!"
+    echo ""
+    echo "cleaning up..."
+
+    cd ..
+    rm -rf $NAME
+    exit
+fi
+echo ""
+
 #Run make
+make -j
+echo ""
+
+echo "Done! If everything went well, you'll find the executable in" $NAME
