HDF5 fixes from Regina Kwee-Hinzmann; This fixes bugs in the HDF5 module, which prevented compilation of HDF5, created runtime errors, and created incorrect physics results (counter was incremented in the wrong place in the code).
This module is enabled by adding the "hdf5" flag to make_six (requiring collimat). It was tested by Regina and Kyrre, and found to produce correct output. When used, the CPU time and disk space requirements for tracks2.dat (replaced by tracks2.h5) go down by a significant factor.

diff --git a/SixTrack/make_six b/SixTrack/make_six
--- a/SixTrack/make_six
+++ b/SixTrack/make_six
@@ -624,29 +624,28 @@ fi
 if test "$hdf5" = ""
 then
     # H5ROOT is the location where you find the  HDF5 libs and include files for your compiler...
-    # Seems the mod files must be created with the EXACT same compiler.
+    # Seems the hdf5.mod files must be created with the EXACT same compiler.
     if test "$gfortran" = ""
     then
-        gccver=`gfortran -dumpversion`
-        if [[ $gccver == 4\.6\.* ]]
+        gccver=`gcc -dumpversion`
+        if [[ $gccver == 4\.4\.* ]]
         then
-            export H5ROOT="/afs/cern.ch/user/y/ylevinse/scratch0/hdf5/hdf5-1.8.7-gcc46"
-        elif [[ $gccver == 4\.5\.* ]]
-        then
-            export H5ROOT="/afs/cern.ch/user/y/ylevinse/scratch0/hdf5/hdf5-1.8.6-gcc45"
-        elif [[ $gccver == 4\.3\.* ]]
-        then
-            export H5ROOT="/afs/cern.ch/user/y/ylevinse/scratch0/hdf5/hdf5-1.8.6-gcc43"
-        else
-            echo "ERROR: hdf5 not available for gcc version $gccver, please disable hdf5 or use gcc version 4.3 or 4.5"
-            exit 1
-        fi
-    elif test "$ifort" = ""
-    then
-            export H5ROOT="/afs/cern.ch/user/y/ylevinse/scratch0/hdf5/hdf5-1.8.7-ifort"
+            # this was compiled for gcc 4.4.7-11 (standard on lxplus, Feb 2015)
+	    export H5ROOT="/afs/cern.ch/user/r/rkwee/public/hdf5/hdf5-1.8.14"
+	    # Alternative:
+            # export H5ROOT="/afs/cern.ch/work/k/kyrsjo/public/codes/hdf5/build-static-lxplus/install"
+	elif [[ $gccver == 4\.8\.* ]]
+	then
+            # this was compiled for gcc 4.8.2 (SLC7, Feb 2015)
+            export H5ROOT="/afs/cern.ch/work/k/kyrsjo/public/codes/hdf5/build-static/install"
+	else
+            echo "ERROR: hdf5 is not available in exactly the same compiler version as gfortran, please disable hdf5. Exiting .."
+	    exit 1
+	fi
     else
-            echo "ERROR: hdf5 not available, please disable hdf5"
-            exit 1
+        echo "ERROR: hdf5 not available, please disable hdf5."
+	echo "hdf5 _MUST_ be compiled with EXACTLY the same compiler version as gfortran was compiled. Exiting"
+        exit 1
     fi
     export FCF="$FCF -I${H5ROOT}/include"
 fi
@@ -711,6 +710,10 @@ fi
 if test "$beamgas" = ""
 then
     ename=$ename"beamgas_"
+fi
+if test "$hdf5" = ""
+then
+    ename=$ename"h5_"
 fi
 ename=$ename$FC
 if test "$fio" = ""
@@ -912,7 +915,7 @@ then
                 # YIL: add hdf5 libs
                 if test "$hdf5" = ""
                 then
-                    export CERNLIB="-Wl,--start-group -L${H5ROOT}/lib32/ -lhdf5 -lhdf5_hl -lhdf5_fortran -lhdf5hl_fortran -lz -lm -Wl,--end-group  $CERNLIB"
+                    export CERNLIB="-Wl,--start-group -I${H5ROOT}/include -L${H5ROOT}/lib -lszip -lhdf5 -lhdf5_hl -lhdf5_fortran -lhdf5_f90cstub -lhdf5_hl_fortran -lz -lm -Wl,--end-group  $CERNLIB"
                 fi
             else
                 echo "Unknown MACHTYPE $MACHTYPE!!"
