Added dummy interface + modifications to sixtrack and make_six. Still need to link them together...

diff --git a/SixTrack/make_six b/SixTrack/make_six
--- a/SixTrack/make_six
+++ b/SixTrack/make_six
@@ -62,7 +62,7 @@ show_options()
 {
     ons="The following selections are ON  :"
     offs="The following selections are OFF :"
-    for i in $( seq 1 30 )
+    for i in $( seq 1 31 )
     do
         if test ${values[$i]} = "true"
         then
@@ -127,9 +127,9 @@ generate_makefile()
 # The 0th option is not used
 declare -a options
 declare -a values
-options=(junk tilt fast crlibm api   cernlib naglib da    collimat cpss  boinc cr    nagfor pgf90 g95   gfortran bpm   beamgas bnlelens bignblz debug hdf5  ifort fio   SSE   lf95  hugenblz stf   bignpart datamods hugenpart)
-values=( junk true true false  false true    true   false false    false false false false  false false false    false false   false    false   false false false false false false false    false false    false    false)
-#Element 0    1    2    3      4     5       6      7     8        9     10    11    12     13    14    15       16    17      18       19      20    21    22    23    24    25    26       27    28       29       30
+options=(junk tilt fast crlibm api   cernlib naglib da    collimat cpss  boinc cr    nagfor pgf90 g95   gfortran bpm   beamgas bnlelens bignblz debug hdf5  ifort fio   SSE   lf95  hugenblz stf   bignpart datamods hugenpart merlinscatter)
+values=( junk true true false  false true    true   false false    false false false false  false false false    false false   false    false   false false false false false false false    false false    false    false false)
+#Element 0    1    2    3      4     5       6      7     8        9     10    11    12     13    14    15       16    17      18       19      20    21    22    23    24    25    26       27    28       29       30    31
 
 # Overide for Darwin
 OSTYPE=`uname -s`
@@ -181,6 +181,7 @@ stf="stf"
 bignpart="bignpart"
 datamods="datamods"
 hugenpart="hugenpart"
+merlinscatter="merlinscatter"
 debug="debug"
 hdf5="hdf5"
 ifort="ifort"
@@ -287,6 +288,9 @@ do
 	-hugenpart) hugenpart="hugenpart"
             values[30]=false
             ;;
+	-merlinscatter) merlinscatter="merlinscatter"
+            values[31]=true
+            ;;
 	
 	#Options to switch things ON
         tilt) tilt=""
@@ -376,6 +380,9 @@ do
             ;;
 	hugenpart) hugenpart=""
 	    values[30]=true
+            ;;
+	merlinscatter) merlinscatter=""
+            values[31]=false
             ;;
 	
 	#Compiler flags are special
@@ -594,6 +601,15 @@ then
     then
 	echo "Option hugenpart requires option datamods."
 	exit 1
+    fi
+fi
+
+if test "$merlinscatter" == ""
+then
+    if test "$collimat" != ""
+    then
+       echo "Option merlinscatter invalid without collimat"
+       exit 1
     fi
 fi
 
@@ -886,7 +902,10 @@ if test "$hugenpart" = ""
 then
     ename=$ename"_hugenpart"
 fi
-
+if test "$merlinscatter" = ""
+then
+    ename=$ename"_merlinscatter"
+fi
 
 if test "$debug" = ""
 then
@@ -994,7 +1013,7 @@ do
 done
 # Update the .ast flags based on options
 echo "Deleting un-used flags and decks from .ast files..."
-for opt in "$crlibm" "$tilt" "$fast" "$bpm" "$beamgas" "$collimat" "$bnlelens" "$cr" "$boinc" "$nagfor" "$bignblz" "$debug" "$hdf5" "$fio" "$lf95" "$hugenblz" "$stf" "$bignpart" "$datamods" "$hugenpart"
+for opt in "$crlibm" "$tilt" "$fast" "$bpm" "$beamgas" "$collimat" "$bnlelens" "$cr" "$boinc" "$nagfor" "$bignblz" "$debug" "$hdf5" "$fio" "$lf95" "$hugenblz" "$stf" "$bignpart" "$datamods" "$hugenpart" "$merlinscatter"
 do
     #echo "opt=" $opt
     if test "$opt" != ""
