Update from Kyrre et al.
What is new:
* DYNK block — documented on
TWIKI: https://twiki.cern.ch/twiki/bin/view/LHCAtHome/SixTrackDoc#Dynamic_Kicks_DYNK_input_block
* DUMP block — documented on
TWIKI: https://twiki.cern.ch/twiki/bin/view/LHCAtHome/SixTrackDoc#Dumping_of_beam_population_DUMP
* DBDCUM for computing s in every element (used for outputting, need to be
always in place) (Alessio)
* Removed RIPP - functionality replaced by DYNK & Documented on TWIKI
* In collimat:
- Make sure all elements are always in place, i.e.
kz=53/54/57/58/59/60/61/62 (crabs), 55 (dipedge), 56 (solenoid)
- Bugfixes for HDF5 (on top of what has already been released)
* Fixes in LINOPT (Alessio):
- De-duplicate writelin calls
- Always initialize variable “k”
- Use bez(jk) (single element inside block) instead of bez(ix) (block
name) for output 
- Always write final bez after block
- Thin tracking+block that is not pure drift -> treat properly 
- Fix trom06
- Correctly handle crabs in collimat
- Element kz > 28: Dump linear optics 
- No jk outside BLOCK loop kz=11: Dump
* Remove nonsense "if(abs(kp(ix).eq. 0 OR 1) -> GOTO 650" from thin6d
* Move file closing code into subroutine “close” (Alessio)
* In make_six:
- Check code using beauty for missed astuce “+ei”
- Check that cr and collimat is not enabled at the same time
- This version / already on SVN
* h5 in exec name if built with HDF5
* Bugfixes for linking etc.
* In beauty:
- Return error to make_six if astuce not closing
* Astuce files sixve.ast & track.ast
- Add support for decks dynkancil, dynktrack, cadcum, close
Main tests that has been ran, all successfully:
* Check DYNKs SET functionality for kz=+1, -1, +2, -2, +3, +4, (+/-1 to
+/- 10 shares most of the code), 23 (voltage/amplitude/phase)
* Check DYNKs FUN functionality / function generation.
* Check Checkpoint/Restart functionality for DYNK and DUMP, including
correct truncation and continuation of output files.
* Check collimation examples
* Check HDF5
* Check that RIPP is exactly reproduced
* Check that SIXTRAC/DYNK/DUMP works with Intel fortran, both standard and
checkpoint/restart version.
* Sixtest tests (run_pro and run_kill): bnl exact crabamp javier thick4
lost tilt dipedge bb notilt lostnotilt lostevery s316 eric frs frs60 bbe51
bbe52 bbe571ib0 distance
All in all, I think the test coverage was quite extensive, and in total we
have probably removed more bugs than we have added.
In total, the code grew by 4943 lines of code (~33 LOC/day), and we also
deleted or modified many many many other lines.
Different executables successfully produced and tested:
./make_six gfortran collimat
./make_six gfortran collimat hdf5
./make_six gfortran crlibm
./make_six gfortran crlibm cr
./make_six ifort crlibm
./make_six ifort crlibm cr
Most of the test notes can be found at (warning: messy and not really
intended for general consumption):
https://www.evernote.com/l/AHNpfE_-KixNka5uH8mK8deDXuSUQ3cm_CA
https://www.evernote.com/l/AHNpfE_-KixNka5uH8mK8deDXuSUQ3cm_CA
https://www.evernote.com/l/AHNxnoAJe15EOax8Z8A49WfhtBmU-OCDpa4
https://www.evernote.com/l/AHPvDfsLTjNF77wIqiFH0M5an9I1A6kHZgo
A complete modified version of the SVN repo folder, comparable to
trunk/Sixtrack, can be found at:
https://github.com/KFubuki/time_dependant_kicks/tree/devel_upstreammerge2 ->
subfolder sixtrack_SVN/sixtrack

Note: This commit was originally two commits in the old SVN repository. There, the files where originally committed with DOS line endings, making the diff go crazy. This was undone in a second commit, here those two are squashed into one.

Also, the second commit included count.awk, which was forgotten in the first commit.

Affected files:
M    ast_mask/sixve.ast
M    ast_mask/track.ast
M    beauty/count.awk
M    make_six
M    sixtrack.s

To see a proper diff (i.e. not all lines), use:
svn diff -x "-w --ignore-eol-style" ast_mask/sixve.ast ast_mask/track.ast beauty/count.awk make_six sixtrack.s

diff --git a/SixTrack/make_six b/SixTrack/make_six
--- a/SixTrack/make_six
+++ b/SixTrack/make_six
@@ -477,6 +477,12 @@ then
     values[12]=true
     echo "Option Checkpoint/Restart turned ON"
 fi
+if test "$collimat" = "" -a "$cr" = ""
+then
+    echo "Options collimat and cr are incompatible - please use only one."
+    exit 1
+fi
+
 # Set up compiler
 if test "$nagfor" = ""
 then
@@ -752,6 +758,20 @@ fi
 ename=${ename}_$myopt
 export ename
 
+#Test that the sixtrack.s is sane
+echo ""
+echo "Running 'gawk -f beauty/count.awk sixtrack.s' to check sanity of astuce directives in sixtrack.s:"
+if ! gawk -f beauty/count.awk sixtrack.s; then
+    echo -e "\e[5m\e[41m WARNING: ASTUCE if/ei doesn't match up in sixtrack.s \e[49m\e[0m"
+    echo "This most likely means that you added or removed a +if or +ei,"
+    echo " but forgot about its partner."
+    echo "You may also just be missing the command 'gawk' (GNU AWK),"
+    echo " needed to run this script."
+else
+    echo "--> count.awk completed without errors."
+fi
+
+#Print final message before actually starting the build
 echo ""
 echo "We are about to build $ename"
 echo "last modified on $moddate"
@@ -789,7 +809,7 @@ else
     export FORS='track sixve sixvefox dabnews lielib beamgas'
 fi
 rm -f *.ast
-for i in $FORS 
+for i in $FORS
 do
     cp ../ast_mask/$i.ast .
 done
@@ -1064,7 +1084,7 @@ show_options
 echo ""
 if test -s "$ename"
 then
-  echo "It appears to have completed successfully."
+  echo -e "\e[92mIt appears to have completed successfully.\e[39m"
   # and a link for Frank
   cd ..
   if test "$da" != ""
@@ -1075,7 +1095,7 @@ then
   fi
   cd $ename
 else
-  echo "It appears to have failed!!!"
+  echo -e "\e[91mIt appears to have failed!!!\e[39m"
   exit 2
 fi
 # Note that selecting boinc has forced cpss
