run count.awk on plato_seq.f

diff --git a/SixTrack/make_six b/SixTrack/make_six
--- a/SixTrack/make_six
+++ b/SixTrack/make_six
@@ -826,6 +826,17 @@ if ! gawk -f beauty/count.awk sixtrack.s; then
 else
     echo "--> count.awk completed without errors."
 fi
+echo "Running 'gawk -f beauty/count.awk plato_seq.s' to check sanity of astuce directives in plato_seq.s:"
+if ! gawk -f beauty/count.awk plato_seq.s; then
+    echo -e "\e[5m\e[41m WARNING: ASTUCE if/ei doesn't match up in plato_seq.s \e[49m\e[0m"
+    echo "This most likely means that you added or removed a +if or +ei,"
+    echo " but forgot about its partner."
+    echo "You may also just be missing the command 'gawk' (GNU AWK),"
+    echo " needed to run this script."
+else
+    echo "--> count.awk completed without errors."
+fi
+
 
 #Print final message before actually starting the build
 echo ""
