SixTrack Version: 4.4.40 eric     -- Same SixTrack but new make_six for MacOS     -- Defaults to ifort instead of lf95     -- uname -m instead of fs sysname     -- sse3 instead of sse2 for Macs     -- enable_xp.c/disable_xp.c dummied on ifdef APPLE     -- Comma separated map options for FCLMAP     -- NO static linking for Mac     -- Fixed bug with make_six options and added lf95    McIntosh 22nd June, 2012

diff --git a/SixTrack/make_six b/SixTrack/make_six
--- a/SixTrack/make_six
+++ b/SixTrack/make_six
@@ -52,7 +52,7 @@ show_options()
 {
     ons="The following selections are ON  :"
     offs="The following selections are OFF :"
-    for i in `seq 1 24`
+    for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
     do
         if test ${values[$i]} = "true"
         then
@@ -101,15 +101,18 @@ generate_makefile()
 # The 0th option is not used
 declare -a options
 declare -a values
-options=(junk tilt tracking fast crlibm api       cernlib naglib da    collimat cpss  boinc cr    nagfor   g77   g95   gfortran bpm beamgas bnlelens bignblz debug hdf5  ifort fio SSE2)
-values=(junk  true true     true false  false     true    true   false false    false false false false    false false false    false false    false   false false false false false false)
+options=(junk tilt tracking fast crlibm api       cernlib naglib da    collimat cpss  boinc cr    nagfor   g77   g95   gfortran bpm beamgas bnlelens bignblz debug hdf5  ifort fio SSE2 lf95)
+values=(junk  true true     true false  false     true    true   false false    false false false false    false false false    false false    false   false false false false false false false)
 
-sysname="`fs sysname`"
+# sysname="`fs sysname`"
+ARCH64="true"
+uname -m | grep 64 > /dev/null
+if test $? != 0
+then
+  ARCH64="false"
+fi
 gfortran_lib=""
-# FORCE build of SixTrack to use 4440 as the VERSION and name
-# but keep the 4437 for BOINC results validation
-#sversion=`grep 'data version' sixtrack.s`
-sversion="/'4.4.40'/"
+sversion=`grep 'data version' sixtrack.s`
 echo $sversion
 # get string between /....../
 sversion=`echo $sversion | sed -e's/.*\/\(.*\)\//\1/'`
@@ -130,7 +133,7 @@ crlibm="NULL"
 cernlib="cernlib"
 naglib="naglib"
 # used for ifort only SSE2
-SSE2="SSE2"
+SSE2="NULL"
 # and we have OFF
 api="api"
 da="da"
@@ -151,7 +154,6 @@ hdf5="hdf5"
 ifort="ifort"
 lf95="lf95"
 fio="fio"
-SSE2=""
 while test $# != 0
 do
     case $1 in
@@ -235,7 +237,10 @@ do
             values[24]=false
             ;;
         -SSE2) SSE2="SSE2"
-            values[24]=false
+            values[25]=false
+            ;;
+        -lf95) lf95="lf95"
+            values[26]=false
             ;;
 
 
@@ -312,7 +317,10 @@ do
             values[24]=true
             ;;
         SSE2) SSE2=""
-            values[24]=true
+            values[25]=true
+            ;;
+        lf95) lf95=""
+            values[26]=true
             ;;
 
     O) myopt=O
@@ -345,6 +353,15 @@ do
     shift
 done
 # Here we do some checking for valid/invalid combinations
+if test "$SSE2" = ""
+then
+  if test "$ifort" != ""
+  then
+    echo "Ignoring SSE2 option (valid for only ifort)"
+    SSE2="SSE2"
+     values[25]=false
+  fi
+fi
 if test "$da" = "" -a "$collimat" = ""
 then
   show_options
@@ -450,85 +467,62 @@ then
     values[12]=true
     echo "Option Checkpoint/Restart turned ON"
 fi
-if test "$crlibm" = ""
-then
-    echo ""
-    echo "NOTA BENE: SKIPPING checks for crlibm !!!"
-    echo "Should really only be specified for tracking with lf95 or ifort!"
-    echo ""
-fi
+#if test "$crlibm" = ""
+#then
+#    echo ""
+#    echo "NOTA BENE: SKIPPING checks for crlibm !!!"
+#    echo "Should really only be specified for tracking with lf95 or ifort!"
+#    echo ""
+#fi
 # Set up compiler
 if test "$nagfor" = ""
 then
-    export FC="nagfor"
-    if test "$myopt" = ""
-    then
-      myopt="O"
-    fi
-# SHOULD I USE -float-store ???? Doesn't seem to be necessary..........
-    export FCF="-$myopt -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full"
-    #export FCF="-$myopt -C=undefined -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full -g90"
-    # export FCF="-float-store -$myopt -C=undefined -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full -g90"
-    # export FCF="-float-store -$myopt -C=all -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full -g90"
-    export FCL="-Bstatic -abi=32"
-    export NAGLIBC="-L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/32 -lg2c"
-elif test "$g77" = ""
-then
-    export FC="g77"
-    if test "$myopt" = ""
-    then
-      myopt="O"
-    fi
-    export FCF="-$myopt -m32 -g -fno-second-underscore -funroll-loops"
-    export FCL="-static -m32"
-elif test "$g95" = ""
-then
-    export FC="g95"
-    if test "$myopt" = ""
-    then
-      myopt="O"
-    fi
-    export FCF="-Wa,--32 -g -fno-second-underscore -funroll-loops"
-    if test "$MACHTYPE" = "i586"
-    then
-        export FCL="-static -m32 -L/usr/lib/ -lc -L/usr/lib/gcc/i586-redhat-linux/4.4.0 -lgcc_eh"
-    else
-        export FCL="-static -m32 -L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/32 -lg2c"
-    fi
-elif test "$gfortran" = ""
-then
-    export FC="gfortran"
-    if test "$myopt" = ""
-    then
-      myopt="O4"
-    fi
-    export FCF="-$myopt -m32 -g -fno-second-underscore -funroll-loops"
-    export FCL="-static -m32"
-elif test "$ifort" = ""
-then
-  export FC="ifort"
+  export FC="nagfor"
   if test "$myopt" = ""
   then
     myopt="O"
   fi
-  if test "$cpss" = "" -o "$crlibm" = ""
+# SHOULD I USE -float-store ???? Doesn't seem to be necessary..........
+  export FCF="-$myopt -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full"
+  #export FCF="-$myopt -C=undefined -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full -g90"
+  # export FCF="-float-store -$myopt -C=undefined -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full -g90"
+  # export FCF="-float-store -$myopt -C=all -abi=32 -dusty -maxcontin=60 -dcfuns -ieee=full -g90"
+  export FCL="-Bstatic -abi=32"
+  export NAGLIBC="-L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/32 -lg2c"
+elif test "$g77" = ""
+then
+  export FC="g77"
+  if test "$myopt" = ""
   then
-# We MUST HAVE the numeric portability (and my default architecture e.g. PIII)
-# Because of performance on AMD etc we allow SSE2 option to optimise
-    if test "$SSE2" = "SSE2"
-    then
-    # Code which works on ANY ia32 WITHOUT using SSE2 though
-      export FCF="-$myopt -mia32 -fp-model source -fp-model strict -fp-model no-except"
-    else
-# and now -mSSE2
-    export FCF="-$myopt -msse2 -fp-model source -fp-model strict -fp-model no-except"
-    fi
-  else
-    # Just use the defaults for the compile host
-    export FCF="-$myopt -m32"
+    myopt="O"
   fi
+  export FCF="-$myopt -m32 -g -fno-second-underscore -funroll-loops"
   export FCL="-static -m32"
-else
+elif test "$g95" = ""
+then
+  export FC="g95"
+  if test "$myopt" = ""
+  then
+    myopt="O"
+  fi
+  export FCF="-Wa,--32 -g -fno-second-underscore -funroll-loops"
+  if test "$MACHTYPE" = "i586"
+  then
+    export FCL="-static -m32 -L/usr/lib/ -lc -L/usr/lib/gcc/i586-redhat-linux/4.4.0 -lgcc_eh"
+  else
+    export FCL="-static -m32 -L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/32 -lg2c"
+  fi
+elif test "$gfortran" = ""
+then
+  export FC="gfortran"
+  if test "$myopt" = ""
+  then
+    myopt="O4"
+  fi
+  export FCF="-$myopt -m32 -g -fno-second-underscore -funroll-loops"
+  export FCL="-static -m32"
+elif test "$lf95" = ""
+then
   export FC="lf95"
   export lf95=""
   if test "$myopt" = ""
@@ -537,7 +531,7 @@ else
   fi
   export FCF="--$myopt --tp -Wa,--32"
   export FCL="-static -m32"
-  if [[ "$MACHTYPE" == *x86_64* ]] 
+  if [[ "$MACHTYPE" == *x86_64* ]]
   then
     ls -l /usr/lib/gcc/x86_64-redhat-linux/4.1.1/32/libgcc_eh.a > /dev/null 2>&1
     if test $? -ne 0
@@ -561,7 +555,47 @@ else
   else
     echo "Unknow MACHTYPE $MACHTYPE"
     exit 2
+  fi
+else
+  if test "$ifort" != ""
+  then
+    echo "Using ifort by default"
+    ifort=""
+    values[23]=true
   fi 
+  export FC="ifort"
+  if test "$myopt" = ""
+  then
+    myopt="O"
+  fi
+  # Turn ON SSE2 unless specifically turned off with -SSE2
+  if test "$SSE2" = "NULL"
+  then
+    SSE2=""
+    values[25]=true
+  fi
+  if test "$cpss" = "" -o "$crlibm" = ""
+  then
+# We MUST HAVE the numeric portability (and my default architecture e.g. PIII)
+# Because of performance on AMD etc we allow SSE2 option to optimise
+    if test "$SSE2" = "SSE2"
+    then
+    # Code which works on ANY ia32 WITHOUT using SSE2 though
+      export FCF="-$myopt -mia32 -fp-model source -fp-model strict -fp-model no-except"
+    else
+# and now -mSSE2
+      if test "$OSTYPE" = "Darwin"
+      then
+        export FCF="-$myopt -msse3 -fp-model source -fp-model strict -fp-model no-except"
+      else
+        export FCF="-$myopt -msse2 -fp-model source -fp-model strict -fp-model no-except"
+      fi
+    fi
+  else
+    # Just use the defaults for the compile host
+    export FCF="-$myopt -m32"
+  fi
+  export FCL="-static -m32"
 fi
 if test "$hdf5" = ""
 then
@@ -600,22 +634,21 @@ else
     export FCLMAP="-Wl,--print-map $FCL"
 fi
 
-if test "$OSTYPE" = "darwin"
+if test "$OSTYPE" = "Darwin"
 then
   # allows running of sixtrack under Macintosh System 10
   echo "MAC setup"
+  # NO STATIC linking? on Darwin
   export FCL="-m32"
-  echo "Operating system: ",$OSTYPE
+  echo "Operating system: $OSTYPE"
 #  FIX up with Frank's fix for 4.6!!!!
   export gfortran_lib="/sw/lib/gcc4.4/lib/libgfortran.a"
   if test "$da" != ""
   then
-    export FCLMAP="-Wl,-map sixtrack.map $FCL"
+    export FCLMAP="-Wl,-map,sixtrack.map $FCL"
   else
-    export FCLMAP="-Wl,-map sixtrack_da.map $FCL"
+    export FCLMAP="-Wl,-map,sixtrack_da.map $FCL"
   fi
-else
-  echo "Linux/windows setup for $sysname / WINDOWS 2000/XP"
 fi
 
 ename="SixTrack_${version}_"
@@ -664,9 +697,12 @@ if test "$api" = ""
 then
     ename=$ename"_api"
 fi
-if test "$SSE2" = ""
+if test "$ifort" = ""
 then
-    ename=$ename"_SSE2"
+  if test "$SSE2" = ""
+  then
+      ename=$ename"_SSE2"
+  fi
 fi
 ename=${ename}_$myopt
 export ename
@@ -840,29 +876,27 @@ then
                 echo "Unknown MACHTYPE $MACHTYPE!!"
             fi
         fi
-    elif test "$OSTYPE" = "darwin"
+    elif test "$OSTYPE" = "Darwin"
     then
         export CERN_ROOT="/sw"
         export CERNLIB="`$CERN_ROOT/bin/cernlib -u graflib packlib kernlib` -lpthread"
     else
-        echo "Unrecognised OSTYPE $OSTYPE (not linux or darwin)"
+        echo "Unrecognised OSTYPE $OSTYPE (not linux or Darwin)"
         exit 2
     fi
 fi
 # and naglib
 if test "$naglib" != ""
 then
-    if test "$sysname" = "Current sysname is 'i386_linux26'"
-    then
-        #SLC4 32 machine
-        export NAGLIB="/afs/cern.ch/sw/nag/mark18/lnx/fllux18dg/libnag.a  -L/usr/lib/gcc/i386-redhat-linux/3.4.3 -lg2c -L/usr/lib -lpthread"
-    elif test "$sysname" = "Current sysname is 'amd64_linux26'"
-    then
-        #SLC4 64 machine
-        export NAGLIB="/afs/cern.ch/sw/nag/mark18/lnx/fllux18dg/libnag.a  -L/usr/lib/gcc/x86_64-redhat-linux/3.4.3/32 -lg2c -L/usr/lib -lpthread"
-    else
-        echo "NAGLIB cannot be found for your machine. SixTrack_da linking will fail!"
-    fi
+  if test "$ARCH64" = "false"
+  then
+    #SLC4 32 machine
+    export NAGLIB="/afs/cern.ch/sw/nag/mark18/lnx/fllux18dg/libnag.a  -L/usr/lib/gcc/i386-redhat-linux/3.4.3 -lg2c -L/usr/lib -lpthread"
+  else
+    #SLC4 64 machine
+    export NAGLIB="/afs/cern.ch/sw/nag/mark18/lnx/fllux18dg/libnag.a  -L/usr/lib/gcc/x86_64-redhat-linux/3.4.3/32 -lg2c -L/usr/lib -lpthread"
+### echo "NAGLIB cannot be found for your machine. SixTrack_da linking will fail!"
+  fi
 fi
 # and crlibm
 export CRLIBM=""
